### ISSUE TITLE
Disbale Auto Log files in FHEM 

### ISSUE THREAD

**Issue by Sonsi79** [oskarn97/fhem-xiaomi-mqtt#1]
Ist es möglich bei deinem FHEM Modul die standardmäßig angelegten log files für die Geräte per def oder attr abzuschalten?
Derzeit lösche ich die beim Pairen angelegte file einfach per Hand aber fände es schöner wenn es optional abschaltbar wäre. 

Hi, is it possible to deactivate the automaticaly generated logfiles in FHEM which are created during pair and „update Devices“

**Comment by oskarn97** [comment]
Hey - das hat mit meinem Modul nichts zu tun sondern ist eine Einstellung bei autocreate.
Lg

**Comment by Sonsi79** [comment]
Oh ok, hatte das nur bei deinem Modul daher dachte ich es kommt daher. 
Danke für deine Flotte Antwort 👍

Hast du evtl. einen schnellen Tipp wo genau ich dies ändern kann?

Lg
