### ISSUE TITLE
Update: "friendly name" gelöscht

### ISSUE THREAD

**Issue by petterpet** [oskarn97/fhem-xiaomi-mqtt#10]
Nach dem Update von gestern (29.12.18) wurde der _friendly name_ gelöscht.
Um diesen wiederherzustellen, muss ich im [NodeRed Admin Panel](https://github.com/ben423423n32j14e/zigbee2mqttadminpanel) zweimal auf _Rename_ klicken, damit die Änderungen wirksam werden.

Nach einem Neustart von FHEM ist der _friendly name_ aber wieder gelöscht.

**Comment by oskarn97** [comment]
Danke! Das liegt daran, dass FHEM nun die Gerätenamen automatisch auf den Friendly Name überträgt. Da du bei dir in FHEM das Gerät wahrscheinlich nicht umbenannt hast, hat er dann den externen Friendly Name zum Gerätenamen zurück benannt. 
Ich habe nun eine Ausnahme eingefügt, dass es nicht umbenannt wird, wenn die Geräte noch den Standardnamen haben und der Friendly Name anders ist.
