### ISSUE TITLE
Probleme mit Internals bei Innr E27 Bulb "RB 175 W"

### ISSUE THREAD

**Issue by eFreshman** [oskarn97/fhem-xiaomi-mqtt#11]
Hi, wenn ich eine RB 175 W anlerne scheint es durch den Namen Problme mit dem Verteilen der Internals zu geben.
Gleich nach dem Anlernen bekomme ich folgende Zuordnungen:
```
Internals:
   CFGFN      
   DEF        RB 175 W 0x00158d0001970b2d
   FRIENDLYNAME W
   IODev      MQTT
   MODEL      RB
   NAME       0x00158d0001970b2d
   NOTIFYDEV  RB 175 W 0x00158d0001970b2d
   NR         1008
   SID        175
   STATE      OFF
   TYPE       XiaomiMQTTDevice
...
   subscribe:
     zigbee2mqtt/W
     xiaomi/175/#
   subscribeExpr:
     ^zigbee2mqtt\/W$
     ^xiaomi\/175.*$
   subscribeQos:
     xiaomi/175/# 0
     zigbee2mqtt/W 0
```
MODEL (RB), SID (175) und FRIENDLYNAME (W) scheinen sich aus der eigndlichen Modelbezeichnung (RB 175 W) abzuleiten. Auch weiß ich nicht ob subscribe so richtig ist.
Vor dem Update hatte ich auch schon Probleme mit dem Namen und ich musste in der configuration.yaml den FRIENDLYNAME auf W anpasen, damit ich schalten kann. Jetzt kam wohl nur dazu das ein Umbenennen des Device in fhem auch den FRIENDLYNAME in der configuration.yaml mit ändert. Es kann aber nur mit W geschaltete werden kann, da die Internals bei W bleiben,
Ist nichts wildes, aber das hat mich u.a. nach dem gestrigen Update etwas aus dem Tritt gebracht.

**Comment by oskarn97** [comment]
Hey!
Danke für den Hinweis - das lag an den Leerzeichen im Modell-Name, ist nun behoben.

**Comment by eFreshman** [comment]
Danke,
funktioniert jetzt prima.
