### ISSUE TITLE
Kein Subscribe auf zigbee2mqtt-Topics

### ISSUE THREAD

**Issue by xtolkien** [oskarn97/fhem-xiaomi-mqtt#2]
Hallo,

nach einem Systemupdate gestern hatte ich das Problem, dass keine Informationen von meine Xiaomi-Geräten nach FHEM durchgereicht wurden. Ich habe FHEM, MQTT und die Xiaomibridge mit dem CC2351-Stick jeweils in einem eigenen Docker-Container laufen. So konnte ich verfolgen, dass die Xiaomibridge ihre Topics an den MQTT-Server schickte. Dort konnte ich sie mit einem anderen MQTT-Client auf meinem Mac verfolgen. Nur das XIAOMIMQTTDEVICE als bridge im FHEM-Container hat nicht reagiert.

Verschickt wurden aber beispielsweise Topics wie updateDevices, die auch korrekt bei der Xiaomibridge ankamen und eine entsprechende Antwort erzeugten.

Nach längerem Suchen habe ich dann noch einen Blick in das Modul 72_XiaomiMQTTDevice.pm geworfen. Da ich Perl nicht beherrsche, war das schon etwas mühsam. Dann habe ich aber in Zeile 116 den Fehler gefunden. Dieser Zweig wird wohl beim Anlegen neuer Attribute ausgeführt. Existiert das Attribute IODEV, so soll ein subscribe auf die notwendigen zigbee2mqtt-Topics ausgeführt werden. Leider ist gerade dieser Subscribe-Anweisung ein # als Kommentar vorangestellt. Also wird nie ein Subscribe ausgeführt. Nachdem ich den Kommentar entfernt habe, läuft wieder alles wie vorher.

Für mich scheint das die Ursache gewesen zu sein.

Viele Grüße
Michael

**Comment by oskarn97** [comment]
Hi Michael,
das subscribe habe ich in das Define verlegt, daher ist es bei den Attributen auskommentiert. Ein Neustart von FHEM hätte ausreichen müssen.

Lg

**Comment by xtolkien** [comment]
Hallo Oskar,
das habe ich auch gesehen. Wenn ich die Systematik richtig verstanden habe, existiert aber doch zum Zeitpunkt des Define noch kein Attribut IODev. Dies wird ja erst mit einem attr angelegt. Daher scheint mir der Subscribe im Define ins Leere zu gehen.

VG
Michael

**Comment by xtolkien** [comment]
Hallo Oskar,
ich hatte mich gestern aus Zeitgründen etwas kurz gefasst. Bevor ich meinen Beitrag verfasst habe, hatte ich schon diverse Neustarts von FHEM gemacht. Deshalb hatte ich mich durch Einfügen von Logausgaben dem Fehler genähert. 

Heute früh habe ich dann noch einmal einen Test gemacht und nochmals verschiedene Log-Ausgaben eingebaut. Dabei kam er wiederum im Define nicht in die if-Anweisung mit dem SubscribeReading, weil zu diesem Zeitpunkt das Attribut IODev noch nicht existiert. Erst das folgende attr-Statement in der fhem.cfg erzeugt ja das Attribut. Dann greift die if-Anweisung im Attr und das SubscribeReading wird ausgeführt.

Dieser Ablauf ist zumindest bei mir so und jederzeit reproduzierbar. Bei Dir scheint es aber anders zu sein, ansonsten hättest Du die Anweisung ja nicht verschoben.

VG
Michael
