### ISSUE TITLE
Log: "unknown attribute subscribeReading_." alle 4 Sekunden

### ISSUE THREAD

**Issue by petterpet** [oskarn97/fhem-xiaomi-mqtt#6]
Hallo,
ich habe heute in meinen FHEM-Log geschaut. 
Dabei ist mir aufgefallen, dass die XiaomiMQTT-Bridge **alle paar Sekunden**, also immer wenn neue Werte über MQTT von der Bridge kommen, `xBridge: unknown attribute subscribeReading_. Type 'attr xBridge ?' for a detailed list.` **in den Log schreibt** und diesen dadurch zumüllt, sodass es ewig dauert die Log-Datei zu öffnen oder der Browser gar ganz abstürzt.
Das genannte Attribut `subscribeReading_.` gibt es an meinem Gerät nicht.

Bitte um schnelle Behebung!

LG

**Comment by cedrik9** [comment]
Selbes Problem gehabt, hab 
attr xBridge userattr subscribeReading_
hinzugefügt und nun keine Einträge mehr.
k.A. ob das richtig ist

**Comment by petterpet** [comment]
> Selbes Problem gehabt, hab
> attr xBridge userattr subscribeReading_
> hinzugefügt und nun keine Einträge mehr.
> k.A. ob das richtig ist

Funktioniert bei mir auch, danke!

**Comment by oskarn97** [comment]
Hey, das Problem sollte mit dem aktuellen Update nun ebenfalls behoben sein.
