### ISSUE TITLE
Update: *** EN FHEM/72_XiaomiMQTTDevice.pm: No document text found

### ISSUE THREAD

**Issue by petterpet** [oskarn97/fhem-xiaomi-mqtt#8]
Hi, habe gerade gesehen, dass es noch ein Update gibt. Habe `update all` ausgeführt und jetzt stoppt der Vorgang mit dem Fehler: `*** EN FHEM/72_XiaomiMQTTDevice.pm: No document text found`.

Update Check gibt:
`
xiaomi-zb2mqtt
List of new / modified files since last update:
UPD FHEM/72_XiaomiMQTTDevice.pm
New entries in the CHANGED file:
404: Not Found`

wobei die letzten beiden Zeilen eben schon so waren.

**Comment by oskarn97** [comment]
Danke, sollte nun passen.

**Comment by petterpet** [comment]
Ja, läuft.
